-- GUESTS
CREATE SEQUENCE GUESTS_ID_SEQ
START WITH 2001
INCREMENT BY 1
NOCACHE; 

-- LISTINGS
CREATE SEQUENCE LISTINGS_ID_SEQ
START WITH 7001
INCREMENT BY 1
NOCACHE;

-- RESERVATIONS
CREATE SEQUENCE RESERVATIONS_ID_SEQ
START WITH 5001
INCREMENT BY 1
NOCACHE;