-- RESERVATIONS
CREATE INDEX R_CHECK_IN_DATE_IDX
ON RESERVATIONS (CHECK_IN_DATE);

-- LISTINGS
CREATE INDEX LI_LISTING_TYPE_IDX
ON LISTINGS (LISTING_TYPE);

-- GUESTS
CREATE INDEX GU_LAST_NAME_IDX
ON GUESTS (LAST_NAME)
