-- GUESTS
BEGIN
    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Emily', 'Johnson', 'emily.johnson@lodgingcrest.com', '3125550192', '123 MAPLE ST', 'CHICAGO', 'IL', '60610', 'Platinum', 1250.00, 'N');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'James', 'Smith', 'james.smith@lodgingcrest.com', '6465550114', '456 Oak Ave', 'New York', 'NY', '10306', 'None', 0.00, 'Y');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Olivia', 'Davis', 'olivia.davis@lodgingcrest.com', '4155550183', '789 Pine Rd', 'San Francisco', 'CA', '94115', 'Gold', 400.00, 'N');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Michael', 'Brown', 'michael.brown@lodgingcrest.com', '3055550177', '321 Elm Blvd', 'Miami', 'FL', '46959', 'Gold', 575.00, 'N');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Sophia', 'Wilson', 'sophia.wilson@lodgingcrest.com', '2145550135', '654 Cedar Ln', 'Dallas', 'TX', '75234', 'Black', 3450.00, 'Y');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'William', 'Miller', 'william.miller@lodgingcrest.com', '2065550123', '987 Spruce Ct', 'Seattle', 'WA', '98122', 'None', 0.00, 'Y');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Ava', 'Moore', 'ava.moore@lodgingcrest.com', '6025550148', '234 Birch St', 'Phoenix', 'AZ', '85282', 'None', 0.00, 'Y');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Benjamin', 'Taylor', 'ben.taylor@lodgingcrest.com', '7045550195', '876 Willow Dr', 'Charlotte', 'NC', '28270', 'Black', 2500.00, 'N');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Mia', 'Anderson', 'mia.anderson@lodgingcrest.com', '3035550111', '147 Aspen Way', 'Denver', 'CO', '80439', 'Platinum', 2000.00, 'Y');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Lucas', 'Thomas', 'lucas.thomas@lodgingcrest.com', '3135550150', '369 Redwood Ave', 'Detroit', 'MI', '48076', 'Platinum', 2175.00, 'Y');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Isabella', 'Jackson', 'isabella.jackson@lodgingcrest.com', '7025550106', '258 Poplar Pl', 'Las Vegas', 'NV', '89101', 'Gold', 1000.00, 'N');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Henry', 'White', 'henry.white@lodgingcrest.com', '9135550162', '112 Magnolia St', 'Kansas City', 'KS', '64086', 'Gold', 750.00, 'N');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Charlotte', 'Harris', 'charlotte.harris@lodgingcrest.com', '5045550180', '734 Dogwood Rd', 'New Orleans', 'LA', '70126', 'None', 0.00, 'N');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Daniel', 'Martin', 'daniel.martin@lodgingcrest.com', '6175550199', '843 Chestnut Ave', 'Boston', 'MA', '2130', 'Black', 4500.00, 'N');

    INSERT INTO GUESTS (GUEST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, ZIP, MEMBERSHIP_STATUS, TOTAL_SPEND, IS_DELINQUENT)
    VALUES (GUESTS_ID_SEQ.NEXTVAL, 'Amelia', 'Thompson', 'amelia.thompson@lodgingcrest.com', '6155550171', '569 Sycamore Blvd', 'Nashville', 'TN', '37215', 'Platinum', 1200.00, 'N');
END;
/

-- HOSTS
INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1001, 'Emma', 'Carter', 'ecarter42@lodgingcrest.com', '4152837194', 'Owner-operated', TO_DATE('2016-06-15', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1002, 'Liam', 'Bennett', 'lbennett39@lodgingcrest.com', '6289173058', 'Property Manager', TO_DATE('2011-03-02', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1003, 'Sophia', 'Reed', 'sreed07@lodgingcrest.com', '3476528801', 'Family-run', TO_DATE('2020-09-28', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1004, 'Noah', 'Mitchell', 'nmitchell84@lodgingcrest.com', '2124876630', 'Family-run', TO_DATE('2013-12-11', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1005, 'Ava', 'Morgan', 'amorgan56@lodgingcrest.com', '5107742349', 'Property Manager', TO_DATE('2023-08-06', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1006, 'Ethan', 'Parker', 'eparker11@lodgingcrest.com', '7023914657', 'Couple', TO_DATE('2012-01-19', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1007, 'Isabella', 'Flores', 'iflores20@lodgingcrest.com', '3035589912', 'Super-host', TO_DATE('2018-11-30', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1008, 'Mason', 'Hughes', 'mhughes95@lodgingcrest.com', '9172438175', 'Couple', TO_DATE('2015-04-09', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1009, 'Mia', 'Sanders', 'msanders68@lodgingcrest.com', '4693847026', 'Family-run', TO_DATE('2021-07-22', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1010, 'Lucas', 'Bryant', 'lbryant73@lodgingcrest.com', '3218001284', 'Family-run', TO_DATE('2010-10-13', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1011, 'Charlotte', 'Rivera', 'crivera16@lodgingcrest.com', '2139853794', 'Couple', TO_DATE('2022-02-17', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1012, 'James', 'Patel', 'jpatel02@lodgingcrest.com', '7186725930', 'Property Manager', TO_DATE('2014-05-01', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1013, 'Amelia', 'Nguyen', 'anguyen87@lodgingcrest.com', '4083104976', 'Property Manager', TO_DATE('2024-03-26', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1014, 'Benjamin', 'Ross', 'bross14@lodgingcrest.com', '6174558023', 'Couple', TO_DATE('2019-09-09', 'YYYY-MM-DD'));

INSERT INTO HOSTS(HOST_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, TYPE, JOIN_DATE)
VALUES(1015, 'Harper', 'Collins', 'hcollins30@lodgingcrest.com', '9542391187', 'Owner-operated', TO_DATE('2017-12-03', 'YYYY-MM-DD'));

-- LISTINGS
BEGIN
    INSERT INTO LISTINGS (LISTING_ID, LISTING_NAME, LISTING_TYPE, LISTING_ADDRESS, CAPACITY, BED_TYPE, DAILY_RATE, DESCRIPTION, AMENITIES, AVAILABILITY_STATUS, HOSTS_HOST_ID)
    VALUES (LISTINGS_ID_SEQ.NEXTVAL, 'The Lakeside Retreat', 'Cottage', '142 Lakeview Drive', 2, 'Queen', 125.00, 'A cozy, stand-alone cottage ideal for romantic getaways.', 'Private deck, kitchenette, gas fireplace, lake view', 'Available', 1002);

    INSERT INTO LISTINGS (LISTING_ID, LISTING_NAME, LISTING_TYPE, LISTING_ADDRESS, CAPACITY, BED_TYPE, DAILY_RATE, DESCRIPTION, AMENITIES, AVAILABILITY_STATUS, HOSTS_HOST_ID)
    VALUES (LISTINGS_ID_SEQ.NEXTVAL, 'The Family Haven', 'Deluxe Room', '28 River Bend Road', 4, 'King + Bunk Beds', 150.00, 'A cottage designed for families', 'Full kitchen, outdoor seating, private patio, living area', 'Available', 1004);

    INSERT INTO LISTINGS (LISTING_ID, LISTING_NAME, LISTING_TYPE, LISTING_ADDRESS, CAPACITY, BED_TYPE, DAILY_RATE, DESCRIPTION, AMENITIES, AVAILABILITY_STATUS, HOSTS_HOST_ID)
    VALUES (LISTINGS_ID_SEQ.NEXTVAL, 'The Rustic Hideaway', 'Cottage', '305 Whispering Pines Lane', 2, 'King', 140.00, 'A charming cottage nestled in the woods, boasting a rustic aesthetic with modern amenities.', 'En-suite bathroom, clawfoot tub, screened porch, secluded location', 'Maintenance', 1001);

    INSERT INTO LISTINGS (LISTING_ID, LISTING_NAME, LISTING_TYPE, LISTING_ADDRESS, CAPACITY, BED_TYPE, DAILY_RATE, DESCRIPTION, AMENITIES, AVAILABILITY_STATUS, HOSTS_HOST_ID)
    VALUES (LISTINGS_ID_SEQ.NEXTVAL, 'The Sunset Bungalow', 'Standard Room', '47 Meadowlark Way', 2, 'Queen', 110.00, 'A bright and airy waterfront cottage with large windows facing the sunset, perfect for quiet escapes or solo retreats.', 'Waterfront view, mini-fridge, outdoor hammock, fire pit, Wi-Fi', 'Booked', 1007);

    INSERT INTO LISTINGS (LISTING_ID, LISTING_NAME, LISTING_TYPE, LISTING_ADDRESS, CAPACITY, BED_TYPE, DAILY_RATE, DESCRIPTION, AMENITIES, AVAILABILITY_STATUS, HOSTS_HOST_ID)
    VALUES (LISTINGS_ID_SEQ.NEXTVAL, 'The Woodland Lodge', 'Cottage', '89 Forest Edge Path', 6, '2 Queen, 1 Sofa Bed', 210.00, 'A spacious lodge-style retreat tucked in the trees, ideal for group vacations.', 'Full kitchen, large deck, BBQ grill, board games, satellite TV', 'Booked', 1003);

    INSERT INTO LISTINGS (LISTING_ID, LISTING_NAME, LISTING_TYPE, LISTING_ADDRESS, CAPACITY, BED_TYPE, DAILY_RATE, DESCRIPTION, AMENITIES, AVAILABILITY_STATUS, HOSTS_HOST_ID)
    VALUES (LISTINGS_ID_SEQ.NEXTVAL, 'The Garden Nook', 'Standard Room', '22 Blossom Street', 3, 'Full + Twin Loft', 135.00, 'A quaint garden-themed cottage surrounded by blooming flowers and ivy-covered trellises, designed for tranquil weekends and creative getaways.', 'Reading nook, writing desk, garden access, tea station, skylight windows', 'Available', 1010);
END;
/

-- RESERVATIONS
BEGIN
    INSERT INTO RESERVATIONS (RESERVATION_ID, CHECK_IN_DATE, CHECK_OUT_DATE, NUM_GUESTS, TOTAL_AMOUNT, AMOUNT_PAID, RESERVATION_STATUS, BOOKING_DATE, NOTES, GUESTS_GUEST_ID, MEMBERSHIP_DEALS_DEAL_ID)
    VALUES (RESERVATIONS_ID_SEQ.NEXTVAL, TO_DATE('2025-06-29', 'YYYY-MM-DD'), TO_DATE('2025-07-01', 'YYYY-MM-DD'), 2, 250.00, 0.00, 'Pending', TO_DATE('2025-06-15', 'YYYY-MM-DD'), 'Extra pillows', 2013, 4006);

    INSERT INTO RESERVATIONS (RESERVATION_ID, CHECK_IN_DATE, CHECK_OUT_DATE, NUM_GUESTS, TOTAL_AMOUNT, AMOUNT_PAID, RESERVATION_STATUS, BOOKING_DATE, NOTES, GUESTS_GUEST_ID, MEMBERSHIP_DEALS_DEAL_ID)
    VALUES (RESERVATIONS_ID_SEQ.NEXTVAL, TO_DATE('2025-07-06', 'YYYY-MM-DD'), TO_DATE('2025-07-11', 'YYYY-MM-DD'), 3, 390.00, 0.01, 'Pending', TO_DATE('2025-06-22', 'YYYY-MM-DD'), 'Gluten-free breakfast', 2008, 4005);

    INSERT INTO RESERVATIONS (RESERVATION_ID, CHECK_IN_DATE, CHECK_OUT_DATE, NUM_GUESTS, TOTAL_AMOUNT, AMOUNT_PAID, RESERVATION_STATUS, BOOKING_DATE, NOTES, GUESTS_GUEST_ID, MEMBERSHIP_DEALS_DEAL_ID)
    VALUES (RESERVATIONS_ID_SEQ.NEXTVAL, TO_DATE('2025-06-12', 'YYYY-MM-DD'), TO_DATE('2025-06-16', 'YYYY-MM-DD'), 4, 600.00, 0.02, 'Pending', TO_DATE('2025-05-29', 'YYYY-MM-DD'), 'Gluten-free breakfast', 2011, 4006);

    INSERT INTO RESERVATIONS (RESERVATION_ID, CHECK_IN_DATE, CHECK_OUT_DATE, NUM_GUESTS, TOTAL_AMOUNT, AMOUNT_PAID, RESERVATION_STATUS, BOOKING_DATE, NOTES, GUESTS_GUEST_ID, MEMBERSHIP_DEALS_DEAL_ID)
    VALUES (RESERVATIONS_ID_SEQ.NEXTVAL, TO_DATE('2025-06-25', 'YYYY-MM-DD'), TO_DATE('2025-06-27', 'YYYY-MM-DD'), 2, 238.00, 0.03, 'Pending', TO_DATE('2025-06-11', 'YYYY-MM-DD'), 'Extra pillows', 2015, 4002);

    INSERT INTO RESERVATIONS (RESERVATION_ID, CHECK_IN_DATE, CHECK_OUT_DATE, NUM_GUESTS, TOTAL_AMOUNT, AMOUNT_PAID, RESERVATION_STATUS, BOOKING_DATE, NOTES, GUESTS_GUEST_ID, MEMBERSHIP_DEALS_DEAL_ID)
    VALUES (RESERVATIONS_ID_SEQ.NEXTVAL, TO_DATE('2025-06-15', 'YYYY-MM-DD'), TO_DATE('2025-06-17', 'YYYY-MM-DD'), 3, 270.00, 0.04, 'Pending', TO_DATE('2025-06-01', 'YYYY-MM-DD'), 'Extra pillows', 2006, 4006);

    INSERT INTO RESERVATIONS (RESERVATION_ID, CHECK_IN_DATE, CHECK_OUT_DATE, NUM_GUESTS, TOTAL_AMOUNT, AMOUNT_PAID, RESERVATION_STATUS, BOOKING_DATE, NOTES, GUESTS_GUEST_ID, MEMBERSHIP_DEALS_DEAL_ID)
    VALUES (RESERVATIONS_ID_SEQ.NEXTVAL, TO_DATE('2025-07-10', 'YYYY-MM-DD'), TO_DATE('2025-07-13', 'YYYY-MM-DD'), 2, 330.00, 0.05, 'Pending', TO_DATE('2025-06-26', 'YYYY-MM-DD'), 'None', 2010, 4006);

    INSERT INTO RESERVATIONS (RESERVATION_ID, CHECK_IN_DATE, CHECK_OUT_DATE, NUM_GUESTS, TOTAL_AMOUNT, AMOUNT_PAID, RESERVATION_STATUS, BOOKING_DATE, NOTES, GUESTS_GUEST_ID, MEMBERSHIP_DEALS_DEAL_ID)
    VALUES (RESERVATIONS_ID_SEQ.NEXTVAL, TO_DATE('2025-06-20', 'YYYY-MM-DD'), TO_DATE('2025-06-22', 'YYYY-MM-DD'), 4, 420.00, 0.06, 'Pending', TO_DATE('2025-06-06', 'YYYY-MM-DD'), 'Gluten-free breakfast', 2012, 4006);
END;
/

-- GUEST_MEMBERSHIP_HISTORYS
INSERT INTO GUEST_MEMBERSHIP_HISTORYS (GUEST_MEMBERSHIP_HISTORY_ID, MEMBERSHIP_TIER, ENROLLMENT_DATE, EXPIRATION_DATE, GUESTS_GUEST_ID)
VALUES (3001, 'None', TO_DATE('2022-06-01', 'YYYY-MM-DD'), TO_DATE('2026-06-09', 'YYYY-MM-DD'), 2013);

INSERT INTO GUEST_MEMBERSHIP_HISTORYS (GUEST_MEMBERSHIP_HISTORY_ID, MEMBERSHIP_TIER, ENROLLMENT_DATE, EXPIRATION_DATE, GUESTS_GUEST_ID)
VALUES (3002, 'Gold', TO_DATE('2023-02-01', 'YYYY-MM-DD'), TO_DATE('2026-02-02', 'YYYY-MM-DD'), 2012);

INSERT INTO GUEST_MEMBERSHIP_HISTORYS (GUEST_MEMBERSHIP_HISTORY_ID, MEMBERSHIP_TIER, ENROLLMENT_DATE, EXPIRATION_DATE, GUESTS_GUEST_ID)
VALUES (3003, 'Gold', TO_DATE('2024-02-02', 'YYYY-MM-DD'), TO_DATE('2026-02-03', 'YYYY-MM-DD'), 2011);

INSERT INTO GUEST_MEMBERSHIP_HISTORYS (GUEST_MEMBERSHIP_HISTORY_ID, MEMBERSHIP_TIER, ENROLLMENT_DATE, EXPIRATION_DATE, GUESTS_GUEST_ID)
VALUES (3004, 'Platinum', TO_DATE('2022-01-01', 'YYYY-MM-DD'), TO_DATE('2027-01-02', 'YYYY-MM-DD'), 2015);

INSERT INTO GUEST_MEMBERSHIP_HISTORYS (GUEST_MEMBERSHIP_HISTORY_ID, MEMBERSHIP_TIER, ENROLLMENT_DATE, EXPIRATION_DATE, GUESTS_GUEST_ID)
VALUES (3005, 'None', TO_DATE('2023-01-02', 'YYYY-MM-DD'), TO_DATE('2026-01-03', 'YYYY-MM-DD'), 2006);

INSERT INTO GUEST_MEMBERSHIP_HISTORYS (GUEST_MEMBERSHIP_HISTORY_ID, MEMBERSHIP_TIER, ENROLLMENT_DATE, EXPIRATION_DATE, GUESTS_GUEST_ID)
VALUES (3006, 'Platinum', TO_DATE('2023-05-01', 'YYYY'), TO_DATE('2027-05-01', 'YYYY-MM-DD'), 2010);

INSERT INTO GUEST_MEMBERSHIP_HISTORYS (GUEST_MEMBERSHIP_HISTORY_ID, MEMBERSHIP_TIER, ENROLLMENT_DATE, EXPIRATION_DATE, GUESTS_GUEST_ID)
VALUES (3007, 'Platinum', TO_DATE('2023-05-04', 'YYYY'), TO_DATE('2028-05-05', 'YYYY-MM-DD'), 2008);

-- MEMBERSHIP_DEALS
INSERT INTO MEMBERSHIP_DEALS (DEAL_ID, DEAL_NAME, DISCOUNT_PERCENTAGE, FIXED_DISCOUNT_AMOUNT, START_DATE, END_DATE, MIN_STAY_NIGHTS, APPLICABLE_LISTING, MEMBERSHIP_TIER_REQUIRED, DEAL_DESCRIPTION)
VALUES (4001, 'Summer Bliss', 10.00, 25.00, TO_DATE('2025-06-01', 'YYYY-MM-DD'), TO_DATE('2025-08-31', 'YYYY-MM-DD'), 3, 'Family Room', 'Gold', 'Enjoy summer with 10% off plus $25 off for 3-night minimum bookings in Family Rooms.');

INSERT INTO MEMBERSHIP_DEALS (DEAL_ID, DEAL_NAME, DISCOUNT_PERCENTAGE, FIXED_DISCOUNT_AMOUNT, START_DATE, END_DATE, MIN_STAY_NIGHTS, APPLICABLE_LISTING, MEMBERSHIP_TIER_REQUIRED, DEAL_DESCRIPTION)
VALUES (4002, 'Winter warmup', 15.00, NULL, TO_DATE('2025-12-01', 'YYYY-MM-DD'), TO_DATE('2026-02-28', 'YYYY-MM-DD'), 2, 'Mountain Cabin', 'Platinum', '15% off winter getaways at Mountain Cabins for Platinum members.');

INSERT INTO MEMBERSHIP_DEALS (DEAL_ID, DEAL_NAME, DISCOUNT_PERCENTAGE, FIXED_DISCOUNT_AMOUNT, START_DATE, END_DATE, MIN_STAY_NIGHTS, APPLICABLE_LISTING, MEMBERSHIP_TIER_REQUIRED, DEAL_DESCRIPTION)
VALUES (4003, 'Midweek Special', 5.00, 20.00, TO_DATE('2025-09-01', 'YYYY-MM-DD'), TO_DATE('2025-11-30', 'YYYY-MM-DD'), 1, 'Standard Lake View Suite', 'Gold', 'Midweek special: 5% off and $20 discount for 1-night stays in Standard Lake View Suites.');

INSERT INTO MEMBERSHIP_DEALS (DEAL_ID, DEAL_NAME, DISCOUNT_PERCENTAGE, FIXED_DISCOUNT_AMOUNT, START_DATE, END_DATE, MIN_STAY_NIGHTS, APPLICABLE_LISTING, MEMBERSHIP_TIER_REQUIRED, DEAL_DESCRIPTION)
VALUES (4004, 'Anniversary Bonus', NULL, 50.00, TO_DATE('2025-07-01', 'YYYY-MM-DD'), TO_DATE('2025-12-31', 'YYYY-MM-DD'), 2, 'Family Room', 'Gold', 'Celebrate your anniversary with $50 off 2-night stays in Family Rooms.');

INSERT INTO MEMBERSHIP_DEALS (DEAL_ID, DEAL_NAME, DISCOUNT_PERCENTAGE, FIXED_DISCOUNT_AMOUNT, START_DATE, END_DATE, MIN_STAY_NIGHTS, APPLICABLE_LISTING, MEMBERSHIP_TIER_REQUIRED, DEAL_DESCRIPTION)
VALUES (4005, 'Extended Stay Deal', 20.00, 100.00, TO_DATE('2025-06-15', 'YYYY-MM-DD'), TO_DATE('2025-12-15', 'YYYY-MM-DD'), 5, 'Mountain Cabin', 'Black', '20% off + $150 off extended stays of 5 nights + in luxury villas for Platinum members only.');

INSERT INTO MEMBERSHIP_DEALS (DEAL_ID, DEAL_NAME, DISCOUNT_PERCENTAGE, FIXED_DISCOUNT_AMOUNT, START_DATE, END_DATE, MIN_STAY_NIGHTS, APPLICABLE_LISTING, MEMBERSHIP_TIER_REQUIRED, DEAL_DESCRIPTION)
VALUES (4006, 'No Deal', NULL, NULL, TO_DATE('2025-01-01', 'YYYY-MM-DD'), NULL, NULL, NULL, NULL, 'No current deal');

-- RESERVATION_LISTINGS
INSERT INTO RESERVATION_LISTINGS (LISTING_RATE_AT_BOOKING, RESERVATIONS_RESERVATION_ID, LISTINGS_LISTING_ID)
VALUES (125.00, 5001, 7001);

INSERT INTO RESERVATION_LISTINGS (LISTING_RATE_AT_BOOKING, RESERVATIONS_RESERVATION_ID, LISTINGS_LISTING_ID)
VALUES (135.00, 5002, 7006);

INSERT INTO RESERVATION_LISTINGS (LISTING_RATE_AT_BOOKING, RESERVATIONS_RESERVATION_ID, LISTINGS_LISTING_ID)
VALUES (150.00, 5003, 7002);

INSERT INTO RESERVATION_LISTINGS (LISTING_RATE_AT_BOOKING, RESERVATIONS_RESERVATION_ID, LISTINGS_LISTING_ID)
VALUES (140.00, 5004, 7003);

INSERT INTO RESERVATION_LISTINGS (LISTING_RATE_AT_BOOKING, RESERVATIONS_RESERVATION_ID, LISTINGS_LISTING_ID)
VALUES (135.00, 5005, 7006);

INSERT INTO RESERVATION_LISTINGS (LISTING_RATE_AT_BOOKING, RESERVATIONS_RESERVATION_ID, LISTINGS_LISTING_ID)
VALUES (110.00, 5006, 7004);

INSERT INTO RESERVATION_LISTINGS (LISTING_RATE_AT_BOOKING, RESERVATIONS_RESERVATION_ID, LISTINGS_LISTING_ID)
VALUES (210.00, 5007, 7005);

-- PAYMENTS
INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, TRANSACTION_DETAILS, PAYMENT_STATUS, RESERVATIONS_RESERVATION_ID)
VALUES (8001, TO_DATE('2025-06-21', 'YYYY-MM-DD'), 300.00, 'Credit Card', '****1234', 'Success', 5001);

INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, TRANSACTION_DETAILS, PAYMENT_STATUS, RESERVATIONS_RESERVATION_ID)
VALUES (8002, TO_DATE('2025-06-29', 'YYYY-MM-DD'), 450.00, 'Cash', NULL, 'Success', 5005);

INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, TRANSACTION_DETAILS, PAYMENT_STATUS, RESERVATIONS_RESERVATION_ID)
VALUES (8003, TO_DATE('2025-06-26', 'YYYY-MM-DD'), 200.00, 'Online Transfer', 'TXN983742', 'Pending', 5002);

INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, TRANSACTION_DETAILS, PAYMENT_STATUS, RESERVATIONS_RESERVATION_ID)
VALUES (8004, TO_DATE('2025-06-22', 'YYYY-MM-DD'), 350.00, 'Cashier''s Check', 'CHK789456', 'Success', 5004);

INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, TRANSACTION_DETAILS, PAYMENT_STATUS, RESERVATIONS_RESERVATION_ID)
VALUES (8005, TO_DATE('2025-06-18', 'YYYY-MM-DD'), 100.00, 'Credit Card', '****5678', 'Failed', 5003);

INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, TRANSACTION_DETAILS, PAYMENT_STATUS, RESERVATIONS_RESERVATION_ID)
VALUES (8006, TO_DATE('2025-06-13', 'YYYY-MM-DD'), 275.00, 'Online Transfer', 'TXN238192', 'Success', 5006);

INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_DATE, AMOUNT, PAYMENT_METHOD, TRANSACTION_DETAILS, PAYMENT_STATUS, RESERVATIONS_RESERVATION_ID)
VALUES (8007, TO_DATE('2025-06-25', 'YYYY-MM-DD'), 500.00, 'Cash', NULL, 'Pending', 5007);
