-- GUESTS
ALTER TABLE GUESTS ADD CONSTRAINT GU_ID_PK PRIMARY KEY (GUEST_ID);

ALTER TABLE GUESTS ADD CONSTRAINT GU_EMAIL_UK UNIQUE (EMAIL);

ALTER TABLE GUESTS ADD CONSTRAINT GU_IS_DELINQUENT_CK
   CHECK (IS_DELINQUENT IN ('Y', 'N'));

-- HOSTS
ALTER TABLE HOSTS ADD CONSTRAINT HO_ID_PK PRIMARY KEY (HOST_ID);

ALTER TABLE HOSTS ADD CONSTRAINT HO_EMAIL_UK UNIQUE (EMAIL);

ALTER TABLE HOSTS ADD CONSTRAINT HO_TYPE_CK
   CHECK (TYPE IN ('Super-host', 'Couple', 'Family-run', 'Property Manager', 'Owner-operated'));

-- LISTINGS
ALTER TABLE LISTINGS ADD CONSTRAINT LI_ID_PK PRIMARY KEY (LISTING_ID);

ALTER TABLE LISTINGS ADD CONSTRAINT LI_NAME_UK UNIQUE (LISTING_NAME);

ALTER TABLE LISTINGS ADD CONSTRAINT LI_AVAILABILITY_STATUS_CK
   CHECK (AVAILABILITY_STATUS IN ('Available', 'Maintenance', 'Booked'));

ALTER TABLE LISTINGS ADD CONSTRAINT LI_TYPE_CK
   CHECK (LISTING_TYPE IN ('Standard Room', 'Deluxe Room', 'Cottage'));

ALTER TABLE LISTINGS
   ADD CONSTRAINT LI_HO_ID_FK FOREIGN KEY (HOSTS_HOST_ID) REFERENCES HOSTS (HOST_ID);

-- RESERVATIONS
ALTER TABLE RESERVATIONS ADD CONSTRAINT R_ID_PK PRIMARY KEY (RESERVATION_ID);

ALTER TABLE RESERVATIONS ADD CONSTRAINT R_RESERVATION_STATUS_CK
   CHECK (RESERVATION_STATUS IN ('Confirmed', 'Pending', 'Cancelled', 'Completed'));

ALTER TABLE RESERVATIONS
   ADD CONSTRAINT R_G_ID_FK FOREIGN KEY (GUESTS_GUEST_ID) REFERENCES GUESTS (GUEST_ID);

ALTER TABLE RESERVATIONS
   ADD CONSTRAINT R_MD_ID_FK FOREIGN KEY (MEMBERSHIP_DEALS_DEAL_ID) REFERENCES MEMBERSHIP_DEALS (DEAL_ID);

-- GUEST_MEMBERSHIP_HISTORYS
ALTER TABLE GUEST_MEMBERSHIP_HISTORYS ADD CONSTRAINT GMH_ID_PK PRIMARY KEY (GUEST_MEMBERSHIP_HISTORY_ID);

ALTER TABLE GUEST_MEMBERSHIP_HISTORYS
   ADD CONSTRAINT GMH_G_ID_FK FOREIGN KEY (GUESTS_GUEST_ID) REFERENCES GUESTS (GUEST_ID);

-- MEMBERSHIP_DEALS
ALTER TABLE MEMBERSHIP_DEALS ADD CONSTRAINT MD_ID_PK PRIMARY KEY (DEAL_ID);

ALTER TABLE MEMBERSHIP_DEALS ADD CONSTRAINT MD_DEAL_NAME_UK UNIQUE (DEAL_NAME);

-- RESERVATION_LISTINGS
ALTER TABLE RESERVATION_LISTINGS ADD CONSTRAINT R_LI_PK PRIMARY KEY (RESERVATIONS_RESERVATION_ID, LISTINGS_LISTING_ID);

ALTER TABLE RESERVATION_LISTINGS
   ADD CONSTRAINT R_LI_LI_ID_FK FOREIGN KEY (LISTINGS_LISTING_ID) REFERENCES LISTINGS (LISTING_ID);

ALTER TABLE RESERVATION_LISTINGS
   ADD CONSTRAINT R_LI_R_ID_FK FOREIGN KEY (RESERVATIONS_RESERVATION_ID) REFERENCES RESERVATIONS (RESERVATION_ID);

-- PAYMENTS
ALTER TABLE PAYMENTS ADD CONSTRAINT P_ID_PK PRIMARY KEY (PAYMENT_ID);

ALTER TABLE PAYMENTS ADD CONSTRAINT P_METHOD_CK
   CHECK (PAYMENT_METHOD IN ('Cash', 'Cashier''s Check', 'Credit Card', 'Online Transfer'));

ALTER TABLE PAYMENTS ADD CONSTRAINT P_STATUS_CK
   CHECK (PAYMENT_STATUS IN ('Success', 'Failed', 'Pending'));

ALTER TABLE PAYMENTS
   ADD CONSTRAINT P_R_ID_FK FOREIGN KEY (RESERVATIONS_RESERVATION_ID) REFERENCES RESERVATIONS (RESERVATION_ID);
