-- GUESTS
CREATE TABLE GUESTS
   		(GUEST_ID          NUMBER (4)     NOT NULL,
   		FIRST_NAME        VARCHAR2 (25)  NOT NULL,
   		LAST_NAME         VARCHAR2 (35)  NOT NULL,
   		EMAIL             VARCHAR2 (35)  NOT NULL,
   		PHONE             VARCHAR2 (11)  NOT NULL,
   		ADDRESS           VARCHAR2 (35)  NOT NULL,
   		CITY              VARCHAR2 (35)  NOT NULL,
   		STATE             VARCHAR2 (3)   NOT NULL,
   		ZIP               VARCHAR2 (25)  NOT NULL,
   		MEMBERSHIP_STATUS VARCHAR2 (25),
   		TOTAL_SPEND       NUMBER (10, 2) DEFAULT 0 NOT NULL,
   		IS_DELINQUENT     CHAR (1)       DEFAULT 'N' NOT NULL); 
 
-- HOSTS
CREATE TABLE HOSTS
  	(HOST_ID     NUMBER (4)    NOT NULL,
   	FIRST_NAME  VARCHAR2 (25) NOT NULL,
   	LAST_NAME   VARCHAR2 (35) NOT NULL,
   	EMAIL       VARCHAR2 (35) NOT NULL,
   	PHONE       VARCHAR2 (11) NOT NULL,
   	TYPE        VARCHAR2 (16) NOT NULL, 
  	JOIN_DATE   DATE          NOT NULL);
 
-- LISTINGS
CREATE TABLE LISTINGS
   	(LISTING_ID         NUMBER (4)    NOT NULL,
  	LISTING_NAME        VARCHAR2 (25) NOT NULL,
   	LISTING_TYPE        VARCHAR2 (25) NOT NULL,
   	LISTING_ADDRESS     VARCHAR2 (35) NOT NULL,
   	CAPACITY            NUMBER (2)    NOT NULL, 
   	BED_TYPE            VARCHAR2 (35) NOT NULL,
   	DAILY_RATE          NUMBER (7, 2) NOT NULL,
   	DESCRIPTION         VARCHAR2 (200) NOT NULL,
   	AMENITIES           VARCHAR2 (100),
   	AVAILABILITY_STATUS VARCHAR2 (35) NOT NULL,
   	HOSTS_HOST_ID       NUMBER (4) );

-- RESERVATIONS
CREATE TABLE RESERVATIONS
   	(RESERVATION_ID          NUMBER (4)    NOT NULL,
   	CHECK_IN_DATE           DATE           NOT NULL,
   	CHECK_OUT_DATE          DATE           NOT NULL,
   	NUM_GUESTS              NUMBER (2)     NOT NULL,
   	TOTAL_AMOUNT            NUMBER (15, 2) NOT NULL,
   	AMOUNT_PAID             NUMBER (15, 2) DEFAULT 0 NOT NULL,
   	RESERVATION_STATUS      VARCHAR2 (25)  NOT NULL,
   	BOOKING_DATE            DATE           NOT NULL,
   	NOTES                   VARCHAR2 (100),
   	GUESTS_GUEST_ID         NUMBER (4)     NOT NULL,
   	MEMBERSHIP_DEALS_DEAL_ID NUMBER (4) );
 
-- GUEST_MEMBERSHIP_HISTORYS
CREATE TABLE GUEST_MEMBERSHIP_HISTORYS
   	(GUEST_MEMBERSHIP_HISTORY_ID NUMBER (4)    NOT NULL,
   	MEMBERSHIP_TIER             VARCHAR2 (25) NOT NULL,
   	ENROLLMENT_DATE             DATE          NOT NULL,
   	EXPIRATION_DATE             DATE,         
   	GUESTS_GUEST_ID             NUMBER (4)    NOT NULL);

-- MEMBERSHIP_DEALS
CREATE TABLE MEMBERSHIP_DEALS
   	(DEAL_ID                 NUMBER (4)    NOT NULL,
   	DEAL_NAME                VARCHAR2 (25)  NOT NULL,
   	DISCOUNT_PERCENTAGE      NUMBER (5, 2), 
   	FIXED_DISCOUNT_AMOUNT    NUMBER (7, 2),
   	START_DATE               DATE           NOT NULL,
   	END_DATE                 DATE,         
   	MIN_STAY_NIGHTS          NUMBER (2),
   	APPLICABLE_LISTING       VARCHAR2 (35),
   	MEMBERSHIP_TIER_REQUIRED VARCHAR2 (35),
   	DEAL_DESCRIPTION         VARCHAR2 (100) NOT NULL);

-- RESERVATION_LISTINGS
CREATE TABLE RESERVATION_LISTINGS
   	(LISTING_RATE_AT_BOOKING NUMBER (10, 2) NOT NULL,
   	RESERVATIONS_RESERVATION_ID NUMBER (4) NOT NULL,
   	LISTINGS_LISTING_ID      NUMBER (4) NOT NULL);

-- PAYMENTS
CREATE TABLE PAYMENTS
   	(PAYMENT_ID         NUMBER (4)          NOT NULL,
   	PAYMENT_DATE        DATE                NOT NULL,
   	AMOUNT              NUMBER (15, 2)      NOT NULL,
   	PAYMENT_METHOD      VARCHAR2 (25)       NOT NULL,
   	TRANSACTION_DETAILS VARCHAR2 (25),
   	PAYMENT_STATUS      VARCHAR2 (25)       NOT NULL,
   	RESERVATIONS_RESERVATION_ID NUMBER (4)  NOT NULL);
